import unittest
import sys
import os
from difflib import SequenceMatcher

# Add the project root to sys.path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from translation.translator import TranslationEngine

class TestTranslationQuality(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        # Initialize translation engine once to save time across multiple tests
        cls.engine = TranslationEngine(from_code="en", to_code="pt")

    def setUp(self):
        # Clear state before each test so incremental_translate acts as full translation
        self.engine.clear_state()

    def test_translation_quality(self):
        """
        Validates the translation quality.
        Uses a predefined English text and an expected Portuguese output,
        then compares it with the result generated by TranslationEngine.
        """
        # Define the English text and the expected Portuguese output
        english_text = "Welcome to our real-time translation application. This is a test to validate the translation quality."
        expected_portuguese = "Bem-vindo ao nosso aplicativo de tradução em tempo real. Este é um teste para validar a qualidade da tradução."
        
        # Generate the translation
        translation, processing_time_ms = self.engine.incremental_translate(english_text)
        
        print(f"\nEnglish Input: {english_text}")
        print(f"Expected PT:   {expected_portuguese}")
        print(f"Actual PT:     {translation}")
        print(f"Time Taken:    {processing_time_ms:.2f} ms")
        
        # Clean both strings for comparison (lower case, remove extra spaces and punctuation)
        def clean_text(text):
            return " ".join(text.lower().replace(".", "").replace(",", "").split())

        clean_expected = clean_text(expected_portuguese)
        clean_actual = clean_text(translation)
        
        # Calculate similarity ratio
        similarity = SequenceMatcher(None, clean_expected, clean_actual).ratio()
        print(f"Similarity Score: {similarity:.2f}")
        
        # We expect a similarity score of at least 0.75 (75%) to consider it a high-quality translation
        # because translation models can paraphrase (e.g., "aplicação" vs "aplicativo").
        self.assertGreaterEqual(
            similarity, 
            0.75, 
            f"Translation quality is below threshold! Expected: '{expected_portuguese}', Got: '{translation}'"
        )

if __name__ == '__main__':
    unittest.main()
